CREATE DATABASE BANKDETAILS;

CREATE TABLE EMPLOYEES (
	EMP_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	DEPARTMENT VARCHAR(100) NOT NULL,
	SALARY DECIMAL(10, 2) DEFAULT 30000.00,
	HIRE_DATE NOT NULL DEFAULT CURRENT_DATE
);

--INSERTING INTO TABLE

INSERT into Employees (FIRST_NAME,LAST_NAME,EMAIL,DEPARTMENT,
SALARY,HIRE_DATE)
VALUES('Prabesh','Oza','oza@gmail.com','Eng',85000,'2024-08-26'),
('Hazel','Ketch','khazel@gmail.com','Architech','75000',CURRENT_DATE)
ON CONFLICT (EMAIL) DO NOTHING;

select * from Employees;